Repository DCNJ-Uket/Uket-FE, pull requests merged in 2024-06, with the labels that each got.

#37 feat: 티켓 예매 API 추가 & 수정된 티켓 예매 가능시간 조회 API
  apps/user/src/api/instance.ts
  apps/user/src/api/show.ts
  apps/user/src/hooks/mutations/useMutationBuyTicket.ts
  apps/user/src/hooks/queries/useQueryReservationList.ts
  apps/user/src/hooks/queries/useQueryTicketingList.ts
  apps/user/src/hooks/useDateTicketParams.ts
  apps/user/src/hooks/useShowSelections.ts
  apps/user/src/hooks/useTicketStackForm.ts
  apps/user/src/pages/buy-ticket/_components/DateActivity.tsx
  apps/user/src/pages/buy-ticket/_components/NextButton.tsx
  apps/user/src/pages/buy-ticket/_components/ReservationList.tsx
  apps/user/src/pages/buy-ticket/_components/ShowList.tsx
  apps/user/src/pages/buy-ticket/_components/TimeActivity.tsx
  apps/user/src/pages/buy-ticket/index.tsx
  apps/user/src/pages/home/_components/FestivalSection.tsx
  apps/user/src/pages/home/index.tsx
  apps/user/src/types/showType.ts
  apps/user/src/utils/useTicketFlow.ts
Labels: ✨ feat

#42 refactor: 홈 화면 배너 구현 방식 변경
  apps/user/src/pages/home/_components/carousel/Carousel.css
  apps/user/src/pages/home/_components/carousel/Carousel.tsx
  apps/user/src/pages/home/_components/carousel/CarouselDotButton.tsx
  apps/user/src/pages/home/_components/carousel/CarouselDotButtonList.tsx
  apps/user/src/pages/home/_components/carousel/CarouselLazyImage.tsx
  apps/user/src/styles/Carousel.css
  packages/ui/src/globals.css
Labels: ⚡️ refactor

#43 refactor: Error fallback 수정 및 추상화 & Error Boundary 연결
  apps/user/src/api/auth.ts
  apps/user/src/api/instance.ts
  apps/user/src/components/CriticalErrorBoundary.tsx
  apps/user/src/components/Nav.tsx
  apps/user/src/components/Profile.tsx
  apps/user/src/components/error/CriticalErrorBoundary.tsx
  apps/user/src/components/error/CustomError.tsx
  apps/user/src/components/error/RetryErrorBoundary.tsx
  apps/user/src/components/fallback/DefaultErrorFallback.tsx
  apps/user/src/components/fallback/LoginErrorFallback.tsx
  apps/user/src/hooks/mutations/useMutationLogin.ts
  apps/user/src/hooks/mutations/useMutationReissue.ts
  apps/user/src/hooks/mutations/useMutationSignup.ts
  apps/user/src/hooks/queries/useQueryUserInfo.ts
  apps/user/src/pages/_app.tsx
  apps/user/src/pages/buy-ticket/_components/DateActivity.tsx
  apps/user/src/pages/buy-ticket/_components/TimeActivity.tsx
  apps/user/src/pages/buy-ticket/index.tsx
  apps/user/src/pages/home/_components/fallback/UnivSelectorErrorFallback.tsx
  apps/user/src/pages/home/index.tsx
  apps/user/src/pages/select-univ/index.tsx
  apps/user/src/pages/signup/index.tsx
  apps/user/src/utils/handleCookie.ts
  apps/user/src/utils/handleToken.ts
Labels: ⚡️ refactor

#47 [style] 티켓 예매 완료 페이지 추가
  apps/user/public/complete3DTicket.png
  apps/user/public/ticketingComplete.png
  apps/user/src/pages/buy-ticket/_components/Activity.tsx
  apps/user/src/pages/buy-ticket/_components/CompleteActivity.tsx
  packages/ui/tailwind.config.ts
Labels: 🎨 style

#48 refactor: Protected Routes 및 코드 리팩토링
  .eslintrc.cjs
  apps/user/.eslintrc.cjs
  apps/user/eslint.config.mjs
  apps/user/public/qrcode.png
  apps/user/src/api/instance.ts
  apps/user/src/components/Logo.tsx
  apps/user/src/components/error/CriticalErrorBoundary.tsx
  apps/user/src/components/error/RetryErrorBoundary.tsx
  apps/user/src/components/fallback/DefaultErrorFallback.tsx
  apps/user/src/hooks/queries/useQueryUserInfo.ts
  apps/user/src/pages/404.tsx
  apps/user/src/pages/_app.tsx
  apps/user/src/pages/ticket-list/_components/QRCode.tsx
  apps/user/src/pages/ticket-list/_components/Ticket.tsx
  apps/user/src/utils/redirects.tsx
  eslint.config.mjs
  packages/ui/.eslintrc.cjs
  packages/ui/eslint.config.mjs
  packages/ui/package.json
  packages/ui/src/components/ui/toast.tsx
  packages/ui/src/components/ui/toaster.tsx
  packages/ui/src/components/ui/use-toast.ts
  pnpm-lock.yaml
Labels: ⚡️ refactor

#50 feat: 예매한 티켓 정보 조회 및 티켓 QR 코드 조회 API 연결
  .eslintrc.cjs
  apps/user/.eslintrc.cjs
  apps/user/eslint.config.mjs
  apps/user/index.html
  apps/user/package.json
  apps/user/public/qrcode.png
  apps/user/src/api/instance.ts
  apps/user/src/api/ticket.ts
  apps/user/src/hooks/queries/useQueryMyTicketList.ts
  apps/user/src/hooks/queries/useQueryTicketQRCode.ts
  apps/user/src/pages/ticket-list/_components/GridItem.tsx
  apps/user/src/pages/ticket-list/_components/QRCode.tsx
  apps/user/src/pages/ticket-list/_components/Ticket.tsx
  apps/user/src/pages/ticket-list/_components/TicketDetail.tsx
  apps/user/src/pages/ticket-list/_components/TicketHeader.tsx
  apps/user/src/pages/ticket-list/_components/TicketListSection.tsx
  apps/user/src/pages/ticket-list/_components/fallback/TicketListSectionFallback.tsx
  apps/user/src/pages/ticket-list/index.tsx
  apps/user/src/store/useMyTicketStore.ts
  apps/user/src/types/ticketType.ts
  apps/user/src/utils/handleTicket.ts
  eslint.config.mjs
  packages/ui/.eslintrc.cjs
  packages/ui/eslint.config.mjs
  pnpm-lock.yaml
Labels: ✨ feat

#56 feat: 어드민 QR 코드 인식 기능
  apps/admin/app/layout.tsx
  apps/admin/app/qr-scan/_components/GreetingHeader.tsx
  apps/admin/app/qr-scan/_components/QRFinderIcon.tsx
  apps/admin/app/qr-scan/_components/QRReaderSection.tsx
  apps/admin/app/qr-scan/_components/QRScanner.tsx
  apps/admin/app/qr-scan/page.tsx
  apps/admin/components/Footer.tsx
  apps/admin/components/Nav.tsx
  apps/admin/package.json
  apps/admin/public/logo.png
  packages/ui/src/components/ui/icon.tsx
  pnpm-lock.yaml
Labels: ✨ feat

#58 style: 어드민 로그인 페이지 구현
  apps/admin/app/(auth)/_components/AuthSection.tsx
  apps/admin/app/(auth)/layout.tsx
  apps/admin/app/(auth)/page.tsx
  apps/admin/app/(main)/layout.tsx
  apps/admin/app/(main)/qr-scan/_components/GreetingHeader.tsx
  apps/admin/app/(main)/qr-scan/_components/QRFinderIcon.tsx
  apps/admin/app/(main)/qr-scan/_components/QRReaderSection.tsx
  apps/admin/app/(main)/qr-scan/_components/QRScanner.tsx
  apps/admin/app/(main)/qr-scan/page.tsx
  apps/admin/app/page.tsx
Labels: 🎨 style

#57 style: 회원정보 조회 페이지 레이아웃 구현
  apps/user/src/components/Nav.tsx
  apps/user/src/components/Profile.tsx
  apps/user/src/hooks/queries/useQueryUserInfo.ts
  apps/user/src/hooks/usePreviousPath.ts
  apps/user/src/pages/buy-ticket/_components/CompleteActivity.tsx
  apps/user/src/pages/myinfo/_components/GeneralInfo.tsx
  apps/user/src/pages/myinfo/_components/InfoItem.tsx
  apps/user/src/pages/myinfo/_components/LogoutModal.tsx
  apps/user/src/pages/myinfo/_components/UnivInfo.tsx
  apps/user/src/pages/myinfo/_components/UserInfoSection.tsx
  apps/user/src/pages/myinfo/index.tsx
  apps/user/src/router.ts
  apps/user/src/types/userType.ts
  packages/ui/package.json
  packages/ui/src/components/ui/switch.tsx
  pnpm-lock.yaml
Labels: 🎨 style

#60 feat: 티켓예매취소 api 연결
  apps/user/src/api/instance.ts
  apps/user/src/api/ticket.ts
  apps/user/src/hooks/mutations/useMutationBuyTicket.ts
  apps/user/src/hooks/mutations/useMutationCancelTicket.ts
  apps/user/src/pages/_app.tsx
  apps/user/src/pages/ticket-list/_components/ConfirmModal.tsx
  apps/user/src/pages/ticket-list/_components/QRCode.tsx
  apps/user/src/pages/ticket-list/_components/Ticket.tsx
  apps/user/src/types/ticketType.ts
  packages/ui/src/components/ui/toaster.tsx
  packages/ui/src/components/ui/use-toast.tsx
Labels: ✨ feat
