Repository DCNJ-Uket/Uket-FE, pull requests merged in 2024-05, with the labels that each got.

#6 [refactor] 소셜 OAuth 로그인 방식 변경 및 회원가입에 백엔드 API 연결
  .env.sample
  src/api/auth.ts
  src/api/instance.ts
  src/constants/auth_url.ts
  src/hooks/mutations/useMutationLogin.ts
  src/hooks/mutations/useMutationSignup.ts
  src/pages/login/[provider]/index.tsx
  src/pages/login/index.tsx
  src/pages/signup/_components/Activity.tsx
  src/pages/signup/_components/CompleteActivity.tsx
  src/pages/signup/_components/MailActivity.tsx
  src/pages/signup/_components/MailAuthActivity.tsx
  src/pages/signup/_components/NameActivity.tsx
  src/pages/signup/_components/NextStepButton.tsx
  src/pages/signup/_components/PhoneActivity.tsx
  src/pages/signup/_components/UnivActivity.tsx
  src/pages/signup/_hooks/useStackForm.ts
  src/router.ts
  src/types/authType.ts
  src/utils/handleToken.ts
Labels: refactor

#8 [chore] husky commit lint 설정
  .eslintrc.cjs
  .husky/commit-msg
  commitlint.config.cjs
  package.json
  yarn.lock
Labels: chore

#11 [style] 랜딩 페이지 레이아웃 구현
  package.json
  public/landingTicket.png
  public/logo.png
  src/api/auth.ts
  src/components/Logo.tsx
  src/components/Nav.tsx
  src/components/ui/select.tsx
  src/hooks/mutations/useMutationSignup.ts
  src/hooks/useStackForm.ts
  src/pages/_app.tsx
  src/pages/home/_components/UnivSelector.tsx
  src/pages/home/index.tsx
  src/pages/login/index.tsx
  src/pages/main/index.tsx
  src/pages/select-univ/_components/UnivItem.tsx
  src/pages/select-univ/index.tsx
  src/pages/signup/_components/Activity.tsx
  src/pages/signup/_components/MailActivity.tsx
  src/pages/signup/_components/MailAuthActivity.tsx
  src/pages/signup/_components/NameActivity.tsx
  src/pages/signup/_components/NextStepButton.tsx
  src/pages/signup/_components/PhoneActivity.tsx
  src/pages/signup/_components/UserTypeActivity.tsx
  src/pages/signup/index.tsx
  src/router.ts
  src/utils/vaildateForm.ts
  tailwind.config.js
  yarn.lock
Labels: 🎨 style

#13 [style] 회원가입 페이지 레이아웃 수정 및 네비게이션 바 로그인 유무 표시
  package.json
  public/signupComplete.png
  public/vite.svg
  src/components/Icon.tsx
  src/components/Nav.tsx
  src/components/provider/SVGProvider.tsx
  src/components/ui/drawer.tsx
  src/components/ui/separator.tsx
  src/hooks/useAuth.ts
  src/main.tsx
  src/pages/signup/_components/CompleteActivity.tsx
  src/pages/signup/_components/MailActivity.tsx
  src/pages/signup/_components/MailAuthActivity.tsx
  src/pages/signup/_components/SearchSelector.tsx
  src/pages/signup/_components/UnivActivity.tsx
  src/pages/signup/_components/UserTypeActivity.tsx
  src/pages/signup/_components/UserTypeItem.tsx
  src/utils/handleToken.ts
  tailwind.config.js
  yarn.lock
Labels: 🎨 style

#17 feat: 회원가입 시 학교 조회 및 학과 조회 기능 연결
  .env.sample
  src/api/instance.ts
  src/api/univ.ts
  src/constants/university_list.ts
  src/hooks/queries/useQueryFestivalUnivList.ts
  src/hooks/queries/useQueryUnivOrMajor.ts
  src/hooks/useDebounce.ts
  src/hooks/useSearch.ts
  src/pages/select-univ/_components/UnivItem.tsx
  src/pages/select-univ/_components/UnivList.tsx
  src/pages/signup/_components/SearchResultSection.tsx
  src/pages/signup/_components/SearchSelector.tsx
  src/types/univType.ts
Labels: ✨ feat

#19 feat: 대학별 진행중인 축제 정보 확인 API 연결 및 카카오 맵 연결
  .env.sample
  index.html
  package.json
  public/marker.png
  src/api/instance.ts
  src/api/univ.ts
  src/components/RetryErrorBoundary.tsx
  src/hooks/queries/useQueryFestivalByUniversity.ts
  src/hooks/queries/useQueryFestivalUnivList.ts
  src/hooks/useCustomMap.ts
  src/hooks/useDotButton.ts
  src/index.css
  src/pages/home/_components/FestivalSection.tsx
  src/pages/home/_components/UnivSelector.tsx
  src/pages/home/_components/carousel/Carousel.tsx
  src/pages/home/_components/carousel/CarouselDotButton.tsx
  src/pages/home/_components/carousel/CarouselLazyImage.tsx
  src/pages/home/_components/fallback/FestivalSectionFallback.tsx
  src/pages/home/_components/map/FestivalMap.tsx
  src/pages/home/index.tsx
  src/pages/select-univ/_components/UnivItem.tsx
  src/pages/select-univ/_components/UnivList.tsx
  src/pages/select-univ/_components/fallback/UnivListFallback.tsx
  src/pages/select-univ/index.tsx
  src/types/univType.ts
  tsconfig.json
  yarn.lock
Labels: ✨ feat

#21 refactor: 회원가입 API 에러 핸들링 적용
  src/api/instance.ts
  src/components/CriticalErrorBoundary.tsx
  src/components/RetryErrorBoundary.tsx
  src/hooks/mutations/useMutationSignup.ts
  src/hooks/useStackForm.ts
  src/main.tsx
  src/pages/_app.tsx
  src/pages/signup/index.tsx
Labels: ⚡️ refactor

#25 refactor: 기타 리팩토링
  package.json
  public/landingBg.png
  public/landingLogo.png
  src/api/auth.ts
  src/api/univ.ts
  src/components/BrandButton.tsx
  src/components/ErrorFallback.tsx
  src/components/Logo.tsx
  src/components/Nav.tsx
  src/components/RetryErrorBoundary.tsx
  src/components/provider/QueryProvider.tsx
  src/hooks/mutations/useMutationLogin.ts
  src/hooks/mutations/useMutationReissue.ts
  src/hooks/mutations/useMutationSignup.ts
  src/hooks/queries/useQueryFestivalByUniversity.ts
  src/hooks/queries/useQueryFestivalUnivList.ts
  src/hooks/useSelectUniversity.ts
  src/index.css
  src/main.tsx
  src/pages/_app.tsx
  src/pages/home/_components/FestivalSection.tsx
  src/pages/home/_components/SectionItem.tsx
  src/pages/home/_components/carousel/Carousel.tsx
  src/pages/home/_components/carousel/CarouselLazyImage.tsx
  src/pages/home/_components/fallback/FestivalSectionSusepnseFallback.tsx
  src/pages/home/_components/fallback/UnivSelectorErrorFallback.tsx
  src/pages/home/_components/fallback/UnivSelectorSuspenseFallback.tsx
  src/pages/home/_components/map/FestivalMap.tsx
  src/pages/home/index.tsx
  src/pages/index.tsx
  src/pages/main/index.tsx
  src/pages/select-univ/_components/UnivItem.tsx
  src/pages/select-univ/_components/UnivList.tsx
  src/pages/select-univ/_components/fallback/UnivListFallback.tsx
  src/pages/select-univ/index.tsx
  src/pages/signup/_components/NextStepButton.tsx
  src/router.ts
  src/styles/Carousel.css
  tailwind.config.js
  yarn.lock
Labels: ⚡️ refactor

#27 [refactor] 대학별 진행중인 축제 조회 API 응답값 수정 및 배너에 사용되는 뱃지 컴포넌트 생성
  src/components/Indicator.tsx
  src/components/ui/badge.tsx
  src/pages/home/_components/carousel/Carousel.tsx
  src/pages/home/_components/carousel/CarouselLazyImage.tsx
  src/types/univType.ts
Labels: ⚡️ refactor

#23 style: 티켓 예매 페이지 레이아웃 구현
  public/whiteLogo.png
  src/components/WhiteLogo.tsx
  src/components/ui/dialog.tsx
  src/hooks/useItemSelect.ts
  src/hooks/useModals.ts
  src/hooks/useTicketSlide.ts
  src/pages/_app.tsx
  src/pages/buy-ticket/_components/Activity.tsx
  src/pages/buy-ticket/_components/CircleButton.tsx
  src/pages/buy-ticket/_components/CompleteActivity.tsx
  src/pages/buy-ticket/_components/DateActivity.tsx
  src/pages/buy-ticket/_components/DateItem.tsx
  src/pages/buy-ticket/_components/HeaderItem.tsx
  src/pages/buy-ticket/_components/NextButton.tsx
  src/pages/buy-ticket/_components/TimeActivity.tsx
  src/pages/buy-ticket/_components/TimeCellItem.tsx
  src/pages/buy-ticket/_components/TimeItem.tsx
  src/pages/buy-ticket/index.tsx
  src/pages/ticket-detail/_components/CellItem.tsx
  src/pages/ticket-detail/_components/ConfirmModal.tsx
  src/pages/ticket-detail/index.tsx
  src/pages/ticket-list/_components/CellItem.tsx
  src/pages/ticket-list/_components/TicketItem.tsx
  src/pages/ticket-list/index.tsx
  src/router.ts
  src/utils/buyTicketFlow.ts
Labels: 🎨 style

#34 feat: 유저 정보 조회 API 연결
  apps/user/src/api/instance.ts
  apps/user/src/api/user.ts
  apps/user/src/components/Nav.tsx
  apps/user/src/components/Profile.tsx
  apps/user/src/hooks/queries/useQueryUserInfo.ts
  apps/user/src/hooks/useAuth.ts
  apps/user/src/types/userType.ts
  packages/typescript-config/vite.json
Labels: ✨ feat
