Repository DCNJ-Uket/Uket-FE, pull requests merged in 2024-12, with the labels that each got.

#113 refactor(admin): 입장 확인 API 메소드 변경
  apps/admin/api/ticket.ts
Labels: ⚡️ refactor

#117 refactor: 로그인 및 회원가입 플로우 수정
  apps/soritor/src/api/auth.ts
  apps/soritor/src/components/Nav.tsx
  apps/soritor/src/hooks/mutations/useMutationLogin.ts
  apps/soritor/src/hooks/mutations/useMutationSignup.ts
  apps/soritor/src/hooks/useStackForm.ts
  apps/soritor/src/pages/signup/_components/MailActivity.tsx
  apps/soritor/src/pages/signup/_components/MailAuthActivity.tsx
  apps/soritor/src/pages/signup/_components/MajorField.tsx
  apps/soritor/src/pages/signup/_components/NameActivity.tsx
  apps/soritor/src/pages/signup/_components/NextStepButton.tsx
  apps/soritor/src/pages/signup/_components/NoUnivModal.tsx
  apps/soritor/src/pages/signup/_components/PhoneActivity.tsx
  apps/soritor/src/pages/signup/_components/UnivActivity.tsx
  apps/soritor/src/pages/signup/_components/UnivField.tsx
  apps/soritor/src/pages/signup/_components/UserIdField.tsx
  apps/soritor/src/pages/signup/_components/UserTypeActivity.tsx
  apps/soritor/src/pages/signup/_components/UserTypeItem.tsx
  apps/soritor/src/utils/stackflow.ts
Labels: ⚡️ refactor

#121 feat: 입금 링크 조회 API 연결
  apps/soritor/src/api/instance.ts
  apps/soritor/src/api/ticket.ts
  apps/soritor/src/components/Indicator.tsx
  apps/soritor/src/hooks/queries/useQueryDepositUrl.ts
  apps/soritor/src/hooks/queries/useQueryMyTicketList.ts
  apps/soritor/src/pages/ticket-list/_components/QRCode.tsx
  apps/soritor/src/pages/ticket-list/_components/Ticket.tsx
  apps/soritor/src/pages/ticket-list/_components/TicketDetail.tsx
  packages/ui/src/components/ui/badge.tsx
Labels: ✨ feat

#123 [refactor] 티켓 예매 플로우 수정
  apps/soritor/src/hooks/queries/useQueryReservationList.ts
  apps/soritor/src/hooks/useTicketStackForm.ts
  apps/soritor/src/pages/_app.tsx
  apps/soritor/src/pages/buy-ticket/_components/Activity.tsx
  apps/soritor/src/pages/buy-ticket/_components/CompleteActivity.tsx
  apps/soritor/src/pages/buy-ticket/_components/DateActivity.tsx
  apps/soritor/src/pages/buy-ticket/_components/NextButton.tsx
  apps/soritor/src/pages/buy-ticket/_components/PerformerSheet.tsx
  apps/soritor/src/pages/buy-ticket/_components/QuestionActivity.tsx
  apps/soritor/src/pages/buy-ticket/_components/QuestionSection.tsx
  apps/soritor/src/pages/buy-ticket/_components/ReservationList.tsx
  apps/soritor/src/pages/buy-ticket/_components/SelectHeader.tsx
  apps/soritor/src/pages/buy-ticket/_components/ShowList.tsx
  apps/soritor/src/pages/buy-ticket/_components/TimeActivity.tsx
  apps/soritor/src/utils/buyTicketFlow.ts
  apps/soritor/src/utils/handleCopyToClipboard.ts
  packages/ui/src/components/ui/icon.tsx
  packages/ui/src/components/ui/input.tsx
  packages/ui/src/components/ui/sheet.tsx
  packages/ui/src/components/ui/textarea.tsx
Labels: ⚡️ refactor

#122 chore: SEO 최적화 및 사용자 분석 툴 적용
  apps/soritor/index.html
  apps/soritor/package.json
  apps/soritor/public/android-chrome-192x192.png
  apps/soritor/public/android-chrome-512x512.png
  apps/soritor/public/apple-touch-icon.png
  apps/soritor/public/favicon-16x16.png
  apps/soritor/public/favicon-32x32.png
  apps/soritor/public/favicon.ico
  apps/soritor/public/robots.txt
  apps/soritor/public/sitemap.xml
  apps/soritor/src/components/DynamicMetaTag.tsx
  apps/soritor/src/main.tsx
  apps/soritor/src/pages/home/index.tsx
  apps/soritor/src/pages/index.tsx
  apps/soritor/src/pages/login/index.tsx
  apps/soritor/src/pages/select-univ/index.tsx
  apps/soritor/vite.config.ts
  pnpm-lock.yaml
Labels: 🧹 chore

#125 [feat] 예매한 티켓 계좌 상세 정보 추가 및 기타 작업
  apps/soritor/.puppeteerrc.cjs
  apps/soritor/package.json
  apps/soritor/src/api/instance.ts
  apps/soritor/src/api/ticket.ts
  apps/soritor/src/components/error/CriticalErrorBoundary.tsx
  apps/soritor/src/components/fallback/QrcodeAndDepositErrorFallback.tsx
  apps/soritor/src/hooks/queries/useQueryDepositUrl.ts
  apps/soritor/src/hooks/queries/useQueryTicketQRCode.ts
  apps/soritor/src/pages/index.tsx
  apps/soritor/src/pages/select-univ/_components/UnivList.tsx
  apps/soritor/src/pages/select-univ/_components/fallback/UnivListFallback.tsx
  apps/soritor/src/pages/select-univ/index.tsx
  apps/soritor/src/pages/ticket-list/_components/QRCode.tsx
  apps/soritor/src/pages/ticket-list/_components/QrcodeAndDeposit.tsx
  apps/soritor/src/pages/ticket-list/_components/Ticket.tsx
  apps/soritor/src/pages/ticket-list/_components/TicketListSection.tsx
  apps/soritor/src/pages/ticket-list/_components/TicketModal.tsx
  apps/soritor/src/types/ticketType.ts
  apps/soritor/vite.config.ts
  packages/ui/src/components/ui/card.tsx
Labels: ✨ feat

#131 [fix] 12/28 회의 내용 반영
  apps/soritor/src/hooks/useDateTicketParams.ts
  apps/soritor/src/pages/_app.tsx
  apps/soritor/src/pages/buy-ticket/_components/CompleteActivity.tsx
  apps/soritor/src/pages/buy-ticket/_components/DateActivity.tsx
  apps/soritor/src/pages/buy-ticket/_components/NextButton.tsx
  apps/soritor/src/pages/buy-ticket/_components/QuestionActivity.tsx
  apps/soritor/src/pages/buy-ticket/_components/QuestionSection.tsx
  apps/soritor/src/pages/home/index.tsx
  apps/soritor/src/pages/myinfo/_components/UserInfoSection.tsx
  apps/soritor/src/pages/myinfo/index.tsx
Labels: ⚒️ fix

#134 [feat] 지인 조회 & 제출 api 연결
  apps/soritor/src/api/instance.ts
  apps/soritor/src/api/survey.ts
  apps/soritor/src/hooks/mutations/useMutationSubmitSurvey.ts
  apps/soritor/src/hooks/queries/useQuerySurveyList.ts
  apps/soritor/src/hooks/useSurveyForm.ts
  apps/soritor/src/pages/buy-ticket/_components/NextButton.tsx
  apps/soritor/src/pages/buy-ticket/_components/QuestionActivity.tsx
  apps/soritor/src/pages/buy-ticket/_components/QuestionSection.tsx
  apps/soritor/src/types/surveyType.ts
Labels: ✨ feat
