Repository DCNJ-Uket/Uket-FE, pull requests merged in 2024-07, with the labels that each got.

#65 refactor: 확인 Modal Toast로 수정
  apps/user/src/hooks/mutations/useMutationCancelTicket.ts
  apps/user/src/pages/buy-ticket/_components/CompleteActivity.tsx
  apps/user/src/pages/myinfo/_components/LogoutModal.tsx
  apps/user/src/pages/ticket-list/_components/ConfirmModal.tsx
Labels: ⚡️ refactor

#66 feat: 사용자 서비스 이메일 인증 API 및 인증 가능한 대학 조회 API 연결
  apps/user/src/api/auth.ts
  apps/user/src/api/email.ts
  apps/user/src/api/univ.ts
  apps/user/src/components/Nav.tsx
  apps/user/src/components/fallback/SelectErrorFallback.tsx
  apps/user/src/components/fallback/SignupErrorFallback.tsx
  apps/user/src/hooks/mutations/useMutationRequestEmailAuth.ts
  apps/user/src/hooks/mutations/useMutationSignup.ts
  apps/user/src/hooks/mutations/useMutationVerifyEmailAuth.ts
  apps/user/src/hooks/queries/useQueryUnivOrMajor.ts
  apps/user/src/hooks/queries/useQueryUniversityList.ts
  apps/user/src/hooks/useStackForm.ts
  apps/user/src/hooks/useTimer.ts
  apps/user/src/pages/signup/_components/MailActivity.tsx
  apps/user/src/pages/signup/_components/MailAuthActivity.tsx
  apps/user/src/pages/signup/_components/MajorField.tsx
  apps/user/src/pages/signup/_components/NextStepButton.tsx
  apps/user/src/pages/signup/_components/SearchResultSection.tsx
  apps/user/src/pages/signup/_components/SearchSelector.tsx
  apps/user/src/pages/signup/_components/UnivActivity.tsx
  apps/user/src/pages/signup/_components/UnivField.tsx
  apps/user/src/pages/signup/_components/UserIdField.tsx
  apps/user/src/pages/signup/index.tsx
  apps/user/src/pages/ticket-list/_components/TicketListSection.tsx
  apps/user/src/store/useEmailAuthStore.ts
  apps/user/src/types/emailType.ts
  apps/user/src/types/univType.ts
  apps/user/src/utils/redirects.tsx
  packages/eslint-config/base.js
  packages/eslint-config/package.json
  packages/ui/tailwind.config.ts
  pnpm-lock.yaml
Labels: ✨ feat

#68 style: 티켓 예매 스타일 수정
  apps/user/src/api/show.ts
  apps/user/src/components/fallback/BuyTicketErrorFallback.tsx
  apps/user/src/hooks/queries/useQueryReservationList.ts
  apps/user/src/hooks/queries/useQueryShowList.ts
  apps/user/src/hooks/useReservationSelection.ts
  apps/user/src/hooks/useReservationUserType.ts
  apps/user/src/hooks/useShowSelections.ts
  apps/user/src/pages/buy-ticket/_components/Activity.tsx
  apps/user/src/pages/buy-ticket/_components/DateActivity.tsx
  apps/user/src/pages/buy-ticket/_components/DateItem.tsx
  apps/user/src/pages/buy-ticket/_components/NextButton.tsx
  apps/user/src/pages/buy-ticket/_components/Overlay.tsx
  apps/user/src/pages/buy-ticket/_components/ReservationList.tsx
  apps/user/src/pages/buy-ticket/_components/SelectHeader.tsx
  apps/user/src/pages/buy-ticket/_components/SelectTicketItem.tsx
  apps/user/src/pages/buy-ticket/_components/ShowList.tsx
  apps/user/src/pages/buy-ticket/_components/TicketContainer.tsx
  apps/user/src/pages/buy-ticket/_components/TicketDivider.tsx
  apps/user/src/pages/buy-ticket/_components/TicketFooter.tsx
  apps/user/src/pages/buy-ticket/_components/TicketHeader.tsx
  apps/user/src/pages/buy-ticket/_components/TimeActivity.tsx
  apps/user/src/pages/buy-ticket/_components/TimeItem.tsx
  apps/user/src/pages/buy-ticket/index.tsx
  apps/user/src/types/showType.ts
Labels: 🎨 style

#70 style: 티켓 확인 페이지 및 티켓 상세 모달 스타일 변경
  apps/user/src/components/Indicator.tsx
  apps/user/src/components/Nav.tsx
  apps/user/src/pages/ticket-list/_components/ConfirmModal.tsx
  apps/user/src/pages/ticket-list/_components/GridItem.tsx
  apps/user/src/pages/ticket-list/_components/QRCode.tsx
  apps/user/src/pages/ticket-list/_components/Ticket.tsx
  apps/user/src/pages/ticket-list/_components/TicketDetail.tsx
  apps/user/src/pages/ticket-list/index.tsx
  apps/user/src/types/ticketType.ts
  packages/ui/src/components/ui/badge.tsx
  packages/ui/src/components/ui/dialog.tsx
  packages/ui/src/components/ui/icon.tsx
Labels: 🎨 style

#73 style: 회원 정보 조회 페이지 스타일 변경
  apps/user/src/pages/myinfo/_components/GeneralInfo.tsx
  apps/user/src/pages/myinfo/_components/InfoContainer.tsx
  apps/user/src/pages/myinfo/_components/InfoItem.tsx
  apps/user/src/pages/myinfo/_components/LogoutModal.tsx
  apps/user/src/pages/myinfo/_components/UnivInfo.tsx
  apps/user/src/pages/myinfo/_components/UserInfoSection.tsx
  apps/user/src/pages/myinfo/index.tsx
  packages/ui/src/components/ui/toast.tsx
Labels: 🎨 style

#76 style: 회원가입 페이지 디자인 수정
  apps/user/src/components/Indicator.tsx
  apps/user/src/components/Logo.tsx
  apps/user/src/pages/home/_components/carousel/Carousel.tsx
  apps/user/src/pages/signup/_components/Activity.tsx
  apps/user/src/pages/signup/_components/CompleteActivity.tsx
  apps/user/src/pages/signup/_components/MailActivity.tsx
  apps/user/src/pages/signup/_components/MailAuthActivity.tsx
  apps/user/src/pages/signup/_components/MajorField.tsx
  apps/user/src/pages/signup/_components/NameActivity.tsx
  apps/user/src/pages/signup/_components/NoUnivModal.tsx
  apps/user/src/pages/signup/_components/PhoneActivity.tsx
  apps/user/src/pages/signup/_components/UnivActivity.tsx
  apps/user/src/pages/signup/_components/UnivField.tsx
  apps/user/src/pages/signup/_components/UserIdField.tsx
  apps/user/src/pages/signup/_components/UserTypeActivity.tsx
  apps/user/src/pages/signup/_components/UserTypeItem.tsx
  apps/user/src/utils/redirects.tsx
  packages/ui/src/components/ui/icon.tsx
  packages/ui/src/components/ui/select.tsx
  packages/ui/tailwind.config.ts
Labels: 🎨 style

#77 feat: 회원정보 수정 api 연결
  apps/user/src/api/user.ts
  apps/user/src/components/Nav.tsx
  apps/user/src/hooks/mutations/useMutationUpdateInfo.ts
  apps/user/src/pages/myinfo/_components/GeneralUserInfoContainer.tsx
  apps/user/src/pages/myinfo/_components/InfoContainer.tsx
  apps/user/src/pages/myinfo/_components/InfoItem.tsx
  apps/user/src/pages/myinfo/_components/LogoutModal.tsx
  apps/user/src/pages/myinfo/_components/UserInfoSection.tsx
  apps/user/src/pages/myinfo/index.tsx
  apps/user/src/types/userType.ts
Labels: ✨ feat

#81 style: 티켓예매 및 회원정보조회 QA 반영
  apps/user/src/pages/buy-ticket/_components/Activity.tsx
  apps/user/src/pages/buy-ticket/_components/DateActivity.tsx
  apps/user/src/pages/buy-ticket/_components/Overlay.tsx
  apps/user/src/pages/buy-ticket/_components/SelectHeader.tsx
  apps/user/src/pages/buy-ticket/_components/TimeActivity.tsx
  apps/user/src/pages/buy-ticket/_components/TimeItem.tsx
  apps/user/src/pages/myinfo/_components/LogoutModal.tsx
  packages/ui/src/components/ui/use-toast.tsx
Labels: 🎨 style

#83 refactor: 회원가입 및 로그인 페이지 스타일 수정
  apps/user/src/components/Nav.tsx
  apps/user/src/pages/login/index.tsx
  apps/user/src/pages/signup/_components/UserTypeActivity.tsx
Labels: ⚡️ refactor

#84 feat: 로그인 유도 모달 생성
  apps/user/src/components/AuthRequiredModalButton.tsx
  apps/user/src/components/BrandButton.tsx
  apps/user/src/hooks/useControlRedirect.ts
  apps/user/src/pages/buy-ticket/index.tsx
  apps/user/src/pages/home/index.tsx
  apps/user/src/pages/index.tsx
  packages/ui/src/components/ui/button.tsx
Labels: ✨ feat

#88 style: 티켓예매 및 회원정보 조회 QA 반영
  apps/user/src/pages/buy-ticket/_components/DateItem.tsx
  apps/user/src/pages/buy-ticket/_components/Overlay.tsx
  apps/user/src/pages/buy-ticket/_components/TimeItem.tsx
  apps/user/src/pages/myinfo/_components/GeneralUserInfoContainer.tsx
  apps/user/src/pages/myinfo/_components/InfoItem.tsx
Labels: 🎨 style

#90 style: activity appbar와 nav바 스타일 통일
  apps/user/src/components/Nav.tsx
  apps/user/src/pages/signup/_components/MailActivity.tsx
  apps/user/src/pages/signup/_components/MailAuthActivity.tsx
  apps/user/src/pages/signup/_components/NameActivity.tsx
  apps/user/src/pages/signup/_components/PhoneActivity.tsx
  apps/user/src/pages/signup/_components/UnivActivity.tsx
  apps/user/src/pages/signup/_components/UserTypeActivity.tsx
Labels: 🎨 style

#63 feat: 어드민 서비스 TanstackQuery 설정 및 입장 확인, 어드민 로그인 API 연결
  apps/admin/api/auth.ts
  apps/admin/api/instance.ts
  apps/admin/api/ticket.ts
  apps/admin/app/(auth)/_components/AuthSection.tsx
  apps/admin/app/(auth)/layout.tsx
  apps/admin/app/(main)/layout.tsx
  apps/admin/app/(main)/qr-scan/_components/QRScanner.tsx
  apps/admin/app/layout.tsx
  apps/admin/app/providers.tsx
  apps/admin/components/Nav.tsx
  apps/admin/constants/error.ts
  apps/admin/hooks/mutations/useMutationLogin.ts
  apps/admin/hooks/mutations/useMutationSignup.ts
  apps/admin/hooks/useLoginForm.ts
  apps/admin/hooks/useProfile.ts
  apps/admin/hooks/useScan.ts
  apps/admin/middleware.ts
  apps/admin/package-lock.json
  apps/admin/package.json
  apps/admin/types/authType.ts
  apps/admin/types/ticketType.ts
  apps/admin/utils/handleError.ts
  apps/admin/utils/handleToken.ts
  pnpm-lock.yaml
Labels: ✨ feat
