Repository DCNJ-Uket/Uket-FE, pull requests merged in 2024-11, with the labels that each got.

#105 [feat] 실시간 입장 확인 API 연결 및 테이블(화면) 구성
  apps/admin/api/entry.ts
  apps/admin/app/(main)/entry-check/_components/EntryCheckSection.tsx
  apps/admin/app/(main)/entry-check/_components/EntryDataTable.tsx
  apps/admin/app/(main)/entry-check/page.tsx
  apps/admin/app/getQueryClient.ts
  apps/admin/app/providers.tsx
  apps/admin/hooks/queries/useQueryEntryList.ts
  apps/admin/package.json
  apps/admin/types/entryType.ts
  apps/admin/vercel.json
  packages/ui/src/components/ui/table.tsx
  pnpm-lock.yaml
Labels: ✨ feat

#107 [style] 어드민 디자인 픽스
  apps/admin/app/(main)/booking-manage/_components/BookingList.tsx
  apps/admin/app/(main)/booking-manage/_components/ManageSection.tsx
  apps/admin/components/Pagination.tsx
  apps/admin/constants/ticketStatus.ts
Labels: 🎨 style

#109 refactor: 어드민 서비스 PC 로그인 시 진입점 변경
  apps/admin/app/(auth)/_components/AuthSection.tsx
  apps/admin/app/(auth)/layout.tsx
  apps/admin/app/(main)/booking-manage/page.tsx
  apps/admin/app/(main)/entry-check/page.tsx
  apps/admin/app/(main)/layout.tsx
  apps/admin/app/layout.tsx
  apps/admin/app/providers.tsx
  apps/admin/components/Footer.tsx
  apps/admin/components/LogoutModal.tsx
  apps/admin/components/Nav.tsx
  apps/admin/components/SideNav.tsx
  apps/admin/hooks/mutations/useMutationLogin.ts
  apps/admin/middleware.ts
  apps/admin/utils/isMobile.ts
  package.json
  pnpm-lock.yaml
Labels: ⚡️ refactor

#111 style: PC 환경 레이아웃 사이즈 변경
  apps/user/src/components/error/CriticalErrorBoundary.tsx
  apps/user/src/hooks/queries/useQueryTicketQRCode.ts
  apps/user/src/pages/_app.tsx
  apps/user/src/pages/buy-ticket/_components/Activity.tsx
  apps/user/src/pages/buy-ticket/_components/DateActivity.tsx
  apps/user/src/pages/buy-ticket/index.tsx
  apps/user/src/pages/home/_components/UnivSelector.tsx
  apps/user/src/pages/home/index.tsx
  apps/user/src/pages/select-univ/_components/UnivList.tsx
  apps/user/src/pages/signup/_components/UnivField.tsx
  apps/user/src/pages/ticket-list/_components/QRCode.tsx
  apps/user/src/pages/ticket-list/_components/Ticket.tsx
  apps/user/src/pages/ticket-list/_components/TicketListSection.tsx
Labels: 🎨 style
